### ISSUE TITLE
Bugs in `Sim.Thomas.Coords`

### ISSUE THREAD

**Issue by rueuntal** [MoBiodiv/MoBspatial#4]
Hi Felix - I'm using your `Sim.Thomas.Coords` function in our sensitivity test for mobr, but there seems to be two bugs under the scenario when sigma is large (ie. the Poisson case):
1. xmax and ymax are undefined, and 
2. species names are defined differently. Here they are defined as numbers (e.g., from 1 to 100), while in the other scenario they are defined as "species" + numbers (e.g., species1, species2, etc.)

Thanks!

**Comment by FelixMay** [comment]
Hi Xiao, thanks for this hint. I will fix it soon. Is it very urgent and should be done today? Otherwise I will try to do it tomorrow afternoon.

**Comment by rueuntal** [comment]
These are necessary for the sensitivity analysis to run; but since we'd
need to merge the commits and get things set up on the cluster first, it's
not super urgent. Tomorrow would be great. Thanks!

**Comment by FelixMay** [comment]
Hello @reuntal I tried to fix the bug. I hope it works now.

**Comment by rueuntal** [comment]
Hi Felix - it's working perfectly now. Thanks!
