### ISSUE TITLE
Packages missing when running from a default R version

### ISSUE THREAD

**Issue by MichaelWohlwend42** [MoBiodiv/MoBspatial#5]
Hey Felix, 
Valentin got the code working on my PC today.
The packages "RandomFields" and "SpadeR" (could only be installed with  install_github('AnneChao/SpadeR')) where missing. So if John wants to teach with this package, maybe a load & install function should take care of that. 
Thanks anyway, it's a great project you have there.

**Comment by FelixMay** [comment]
Hi Michael,
Thanks for the hint. But does this really concern my package “MoBspatial” or the package “mobr”. I think the latter, right?
Then I will forward your response to the mobr developers, but I think they did anyways not bundle there code in a formal package so far.

Best,

Felix

Von: MichaelWohlwend42 [mailto:notifications@github.com]
Gesendet: Donnerstag, 6. Oktober 2016 16:44
An: MoBiodiv/MoBspatial <MoBspatial@noreply.github.com>
Betreff: [MoBiodiv/MoBspatial] Packages missing when running from a default R version (#5)


Hey Felix,
Valentin got the code working on my PC today.
The packages "RandomFields" and "SpadeR" (could only be installed with install_github('AnneChao/SpadeR')) where missing. So if John wants to teach with this package, maybe a load & install function should take care of that.
Thanks anyway, it's a great project you have there.
